[general]
import = ["kanagawa_wave.toml"]

[colors]
transparent_background_colors = true

[font]
size = 14
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }
# normal = { family = "RobotoMono Nerd Font", style = "Regular" }
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
# opacity = 0.93
