import = ["/home/olexandr/.config/alacritty/kanagawa_wave.toml"]

[colors]
transparent_background_colors = true

[colors.primary]
foreground = "#95a6b8"

[font]
size = 11.0

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "Hack Nerd Font Mono"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
opacity = 0.90

[window.padding]
x = 5
y = 5
