import = ["/home/olexandr/.config/alacritty/kanagawa_wave.toml"]

[colors]
transparent_background_colors = true

[font]
size = 11
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 2 }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
opacity = 0.90
