import = ["/home/olexandr/.config/alacritty/kanagawa_wave.toml"]

[colors]
transparent_background_colors = true

[font]
size = 11

[font.normal]
family = "Hack Nerd Font Mono"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
opacity = 0.90

# [window.padding]
# x = 5
# y = 5
