theme = "kanagawa"
[editor]
completion-timeout = 5
line-number = "relative"

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "VISUAL"

left = ["mode", "read-only-indicator", "file-name", "file-modification-indicator"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["spinner", "version-control"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
s = ":update"
S = ":write-all"
q = ":q"
Q = ":q!"
c = ":buffer-close"
C = ":buffer-close!"
