theme = "autumn_night"

[editor]
completion-timeout = 5
line-number = "relative"
auto-info = false

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "read-only-indicator", "file-name", "file-modification-indicator", "spacer", "diagnostics"]
center = ["workspace-diagnostics",]
right = ["spinner", "version-control"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
s = ":update"
S = ":write-all"
q = ":q"
Q = ":q!"
c = ":buffer-close"
C = ":buffer-close!"

[keys.normal]
A-l = ":buffer-next"
A-h = ":buffer-previous"
