theme = "kanagawa"
[editor]
completion-timeout = 5
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

left = ["read-only-indicator", "file-name", "file-modification-indicator"]
center = ["mode", "spinner"]
right = ["diagnostics", "workspace-diagnostics", "version-control", "spacer"]

[keys.normal]
C-p = "signature_help"
C-w = "save_selection"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
s = ":update"
S = ":write-all"
  q = ":q"
Q = ":q!"
c = ":buffer-close"
C = ":buffer-close!"
